# Generated by Django 5.2.8 on 2025-11-20 03:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commercant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("contact", models.CharField(max_length=20)),
                ("type_commerce", models.CharField(max_length=100)),
                ("date_inscription", models.DateField(auto_now_add=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Commerçant",
                "verbose_name_plural": "Commerçants",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Secteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Secteur",
                "verbose_name_plural": "Secteurs",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_utilisation", models.DateTimeField(blank=True, null=True)),
                ("utilise", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Etal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20, unique=True)),
                (
                    "superficie",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("libre", "Libre"), ("occupe", "Occupé")],
                        default="libre",
                        max_length=10,
                    ),
                ),
                ("date_attribution", models.DateField(blank=True, null=True)),
                (
                    "commercant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="etals",
                        to="market.commercant",
                    ),
                ),
                (
                    "secteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etals",
                        to="market.secteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étal",
                "verbose_name_plural": "Étals",
                "ordering": ["secteur", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("date_paiement", models.DateTimeField(auto_now_add=True)),
                (
                    "mode_paiement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("mobile_money", "Mobile Money"),
                        ],
                        default="especes",
                        max_length=20,
                    ),
                ),
                (
                    "commercant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="market.commercant",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements_enregistres",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "etal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements",
                        to="market.etal",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paiements",
                        to="market.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="PaiementMensuel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mois", models.IntegerField()),
                ("annee", models.IntegerField()),
                (
                    "montant_attendu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("date_echeance", models.DateField()),
                ("paye", models.BooleanField(default=False)),
                (
                    "commercant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_mensuels",
                        to="market.commercant",
                    ),
                ),
                (
                    "etal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements_mensuels",
                        to="market.etal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement Mensuel",
                "verbose_name_plural": "Paiements Mensuels",
                "ordering": ["-annee", "-mois"],
                "unique_together": {("commercant", "etal", "mois", "annee")},
            },
        ),
    ]
