# Generated by Django 5.2.8 on 2025-12-13 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoriqueAttribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "attribue_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attributions_realisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commercant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_etals",
                        to="market.commercant",
                    ),
                ),
                (
                    "etal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_attributions",
                        to="market.etal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'attribution",
                "verbose_name_plural": "Historique d'attribution",
                "ordering": ["-date_debut"],
            },
        ),
    ]
