# Generated by Django 4.2.26 on 2025-12-15 23:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market", "0003_ticket_statut"),
    ]

    operations = [
        migrations.AddField(
            model_name="etal",
            name="tarif_par_metre_carre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tarif spécifique par m² pour cet étal (optionnel)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="secteur",
            name="jour_echeance",
            field=models.IntegerField(
                default=31,
                help_text="Jour du mois pour l'échéance (1-31, 31 = dernier jour du mois)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(31),
                ],
            ),
        ),
        migrations.AddField(
            model_name="secteur",
            name="tarif_par_defaut",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5000.00"),
                help_text="Tarif par défaut par m² en FCFA",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("retard", "Retard de paiement"),
                            ("attribution", "Attribution d'étal"),
                            ("liberation", "Libération d'étal"),
                            ("paiement", "Nouveau paiement"),
                            ("alerte", "Alerte"),
                            ("info", "Information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("lue", models.BooleanField(default=False)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_lecture", models.DateTimeField(blank=True, null=True)),
                (
                    "lien",
                    models.URLField(
                        blank=True, help_text="URL optionnelle vers l'objet concerné"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-date_creation"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date_creation"],
                        name="market_noti_user_id_828f12_idx",
                    ),
                    models.Index(
                        fields=["user", "lue", "-date_creation"],
                        name="market_noti_user_id_45a9f1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("view", "Consultation"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="Nom du modèle concerné", max_length=100
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=200)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Changements effectués (ancien/nouveau)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Succès"),
                            ("error", "Erreur"),
                            ("warning", "Avertissement"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Message d'erreur ou description"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="market_audi_timesta_8d466d_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="market_audi_user_id_a41842_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="market_audi_model_n_d7c865_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="market_audi_action_36123e_idx",
                    ),
                ],
            },
        ),
    ]
