# Generated by Django 5.0.1 on 2026-01-14

from decimal import Decimal
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0004_etal_tarif_par_metre_carre_secteur_jour_echeance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxeJournaliere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "montant_attendu",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("paye", models.BooleanField(default=False)),
                (
                    "statut",
                    models.CharField(
                        choices=[("du", "Dû"), ("paye", "Payé"), ("annule", "Annulé")],
                        default="du",
                        max_length=20,
                    ),
                ),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "commercant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes_journalieres",
                        to="market.commercant",
                    ),
                ),
                (
                    "etal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxes_journalieres",
                        to="market.etal",
                    ),
                ),
                (
                    "paiement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="taxe_journaliere",
                        to="market.paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Taxe journalière",
                "verbose_name_plural": "Taxes journalières",
                "ordering": ["-date"],
                "unique_together": {("date", "etal")},
                "indexes": [
                    models.Index(fields=["-date"], name="market_taxe_date_idx"),
                    models.Index(fields=["etal", "-date"], name="market_taxe_etal_date_idx"),
                    models.Index(fields=["commercant", "-date"], name="market_taxe_com_date_idx"),
                    models.Index(fields=["paye", "-date"], name="market_taxe_paye_date_idx"),
                ],
            },
        ),
    ]
