# Generated by Django 5.0.1 on 2026-01-14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0005_taxejournaliere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="date_paiement",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
