# Generated by Django 5.0.1 on 2026-01-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0006_alter_paiement_date_paiement"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paiement",
            constraint=models.UniqueConstraint(fields=("ticket",), name="unique_paiement_par_ticket"),
        ),
    ]
