# Generated by Django 5.0.1 on 2026-01-15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0007_unique_paiement_par_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaiementMensuel",
        ),
    ]
