# Generated by Django 5.2.8 on 2026-01-15 00:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0008_delete_paiementmensuel"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collecteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("contact", models.CharField(blank=True, max_length=20)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Collecteur",
                "verbose_name_plural": "Collecteurs",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="LotTickets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_remise", models.DateField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[("ouvert", "Ouvert"), ("clos", "Clos")],
                        default="ouvert",
                        max_length=10,
                    ),
                ),
                (
                    "ticket_debut",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("ticket_fin", models.CharField(blank=True, max_length=20, null=True)),
                ("date_cloture", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Lot de tickets",
                "verbose_name_plural": "Lots de tickets",
                "ordering": ["-date_remise", "-id"],
            },
        ),
        migrations.RenameIndex(
            model_name="taxejournaliere",
            new_name="market_taxe_date_57ebc0_idx",
            old_name="market_taxe_date_idx",
        ),
        migrations.RenameIndex(
            model_name="taxejournaliere",
            new_name="market_taxe_etal_id_5d0822_idx",
            old_name="market_taxe_etal_date_idx",
        ),
        migrations.RenameIndex(
            model_name="taxejournaliere",
            new_name="market_taxe_commerc_405546_idx",
            old_name="market_taxe_com_date_idx",
        ),
        migrations.RenameIndex(
            model_name="taxejournaliere",
            new_name="market_taxe_paye_c88703_idx",
            old_name="market_taxe_paye_date_idx",
        ),
        migrations.AddField(
            model_name="ticket",
            name="motif",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="statut",
            field=models.CharField(
                choices=[
                    ("disponible", "Disponible"),
                    ("utilise", "Utilisé"),
                    ("annule", "Annulé"),
                    ("perdu", "Perdu"),
                ],
                default="disponible",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="collecteur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements",
                to="market.collecteur",
            ),
        ),
        migrations.AddField(
            model_name="lottickets",
            name="collecteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lots",
                to="market.collecteur",
            ),
        ),
        migrations.AddField(
            model_name="lottickets",
            name="remis_par",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lots_remis",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="market.lottickets",
            ),
        ),
    ]
