# Generated by Django 5.2.8 on 2026-01-15 00:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0009_collecteur_lottickets_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lottickets",
            constraint=models.UniqueConstraint(
                fields=("collecteur",),
                condition=Q(statut="ouvert"),
                name="unique_lot_ouvert_par_collecteur",
            ),
        ),
    ]
