# Generated by Django 6.0.1 on 2026-01-19 03:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0010_unique_lot_ouvert_par_collecteur"),
    ]

    operations = [
        migrations.CreateModel(
            name="RapportJournalierCollecteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rapport", models.DateField()),
                ("total_tickets_remis", models.IntegerField(default=0)),
                ("total_tickets_utilises", models.IntegerField(default=0)),
                ("total_tickets_perdus_annules", models.IntegerField(default=0)),
                ("total_tickets_restants", models.IntegerField(default=0)),
                (
                    "total_montant_collecte",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("nombre_paiements", models.IntegerField(default=0)),
                ("nombre_commercants_distincts", models.IntegerField(default=0)),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "collecteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_journaliers",
                        to="market.collecteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport journalier collecteur",
                "verbose_name_plural": "Rapports journaliers collecteurs",
                "ordering": ["-date_rapport", "collecteur"],
                "indexes": [
                    models.Index(
                        fields=["collecteur", "-date_rapport"],
                        name="market_rapp_collect_560939_idx",
                    ),
                    models.Index(
                        fields=["-date_rapport"], name="market_rapp_date_ra_17d375_idx"
                    ),
                ],
                "unique_together": {("collecteur", "date_rapport")},
            },
        ),
        migrations.CreateModel(
            name="RapportMensuelCollecteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.IntegerField()),
                ("mois", models.IntegerField()),
                ("total_tickets_remis", models.IntegerField(default=0)),
                ("total_tickets_utilises", models.IntegerField(default=0)),
                ("total_tickets_perdus_annules", models.IntegerField(default=0)),
                ("total_tickets_restants", models.IntegerField(default=0)),
                (
                    "total_montant_collecte",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("nombre_paiements", models.IntegerField(default=0)),
                ("nombre_commercants_distincts", models.IntegerField(default=0)),
                ("nombre_jours_actifs", models.IntegerField(default=0)),
                (
                    "moyenne_journaliere",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("meilleur_jour", models.DateField(blank=True, null=True)),
                (
                    "meilleur_jour_montant",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "collecteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapports_mensuels",
                        to="market.collecteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport mensuel collecteur",
                "verbose_name_plural": "Rapports mensuels collecteurs",
                "ordering": ["-annee", "-mois", "collecteur"],
                "indexes": [
                    models.Index(
                        fields=["collecteur", "-annee", "-mois"],
                        name="market_rapp_collect_e991bd_idx",
                    ),
                    models.Index(
                        fields=["-annee", "-mois"], name="market_rapp_annee_5e4724_idx"
                    ),
                ],
                "unique_together": {("collecteur", "annee", "mois")},
            },
        ),
    ]
